### ISSUE TITLE
Trouble Building the VM

### ISSUE THREAD

**Issue by cyrus104** [bastibl/instant-gnuradio#10]
Thank you for doing all the leg work for us on this one. I'm having a hard time building it at the moment.

I clone your repo then run ./configure and make. I see the VM being created that apt packages being install but then I get the error below.

![image](https://user-images.githubusercontent.com/1534067/41813508-617ca480-7705-11e8-8b30-72d5181a5f0c.png)

**Comment by bastibl** [comment]
I'm having issues with this from time to time :-/ I just pushed some changes so that a fixed version of Spacemacs is checked out (instead of the development version). Could you give it another try?

**Comment by cyrus104** [comment]
So far so good, I'm on to building pybombs! Will let you know when it's done.

**Comment by cyrus104** [comment]
Well, I made it much farther but now it looks like an opencl issue for fospher.

![image](https://user-images.githubusercontent.com/1534067/41821320-c3cf732c-77ac-11e8-88e4-124760f6ecad.png)

**Comment by bastibl** [comment]
grrr, sorry for this. I rebuilt the whole thing today without problems :-/

Since there is no Fosphor `build` directory, the error suggests that there were previous issues installing Fosphor through PyBombs. (It seems like PyBombs doesn't return a non-zero exit status if something failed. So the installation process might have continued and failed at a later stage.)

**Comment by cyrus104** [comment]
I'm in the process of rebuilding it now. Hopefully it will get a little farther.

I didn't think of it before but I need to make a change to prevent a deleting of the vm if it fails.

Update: I added -on-error=ask to the Makefile and am in the process of a new build.

**Comment by bastibl** [comment]
If you want better error handling you'd have to adapt the installation script `scripts/setup_gnuradio.sh`, but it already has `set -exu`. So you'd have to configure PyBombs to return an error code if there is a problem.

You shouldn't have to care about the VM. If the build fails it gets deleted. So usually there are no left-overs that need manual cleanup.

**Comment by cyrus104** [comment]
I'm still working through it but looks like there might be an error that I'm having is with the mirror.

![image](https://user-images.githubusercontent.com/1534067/41882101-f80834fe-78b4-11e8-8818-98070c8421a2.png)

**Comment by cyrus104** [comment]
I know I took the hard way but I added a file asset that was the US sources.list and then added a "sudo cp -f assets/sources.list /etc/apt/sources.list" to the init-setup.sh file.

This allowed me to successfully build the VM, I'm not sure why the default install is using the DE archive ubuntu servers (since they are all rysnc mirrored it shouldn't matter).
Thank you for taking a look at this for me.

**Comment by bastibl** [comment]
Thanks, good to know. I had the same problems also with other mirrors and, IIRC, the generic mirror was incredible slow. So I'm not really sure how to fix that :-/

**Comment by cyrus104** [comment]
Yeah, for home and office I keep a mirror of the repo and keep it pointed to the generic so my local speed is super fast.

I know it's not your build but with an ettus and hackrf, I can do a test listening to FM on gqrx but when I do a basic test in GnuRadio I get a bunch of audio underruns (aU).

**Comment by cyrus104** [comment]
This build has been super useful but I wanted to see about changing the default repo to either the default us one or one that can be easily changed. For some reason, whenever I do an update and forget to merge my code the "default" repo in this build always have file size issues. As soon as a I change the repo in the vm and then build out gnuradio it works fine.

Thanks!

**Comment by bastibl** [comment]
At the moment, it uses the default repo (archive.ubuntu.com). I think that's the best option for a generic build. (Do you have an other suggestion?)

You can adapt the mirror here:
https://github.com/bastibl/instant-gnuradio/blob/master/preseed.cfg#L6-L7

If you just delete these lines it will fall back to US, since the country is set to US.

**Comment by cyrus104** [comment]
I had to remove the L8 proxy line too but after that it's working. Pulling from a repo on the LAN is so much faster for building.

Thank you for pointing out those lines.
