### ISSUE TITLE
Build GnuRadio VM issue:Cannot open load file: No such file or directory, bind-map

### ISSUE THREAD

**Issue by wangmu0579** [bastibl/instant-gnuradio#13]
Good job done Bastibl.
Met virtualbox-iso problem. 
Have tried twice but still the same problem which start from beginning.
Could you have a look and instruct me how to continue the build not start from beginning?

    virtualbox-iso: Checking /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0...
    virtualbox-iso: Compiling /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/yasnippet-autoloads.el...
    virtualbox-iso: Compiling /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/yasnippet-debug.el...
    virtualbox-iso: Compiling /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/yasnippet-pkg.el...
    virtualbox-iso: Compiling /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/yasnippet-tests.el...
    virtualbox-iso: Compiling /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/yasnippet.el...
    virtualbox-iso: Checking /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/doc...
    virtualbox-iso: Compiling /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/doc/yas-doc-helper.el...
    virtualbox-iso: Checking /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/doc/images...
    virtualbox-iso: Checking /home/gnuradio/.emacs.d/elpa/25.2/yasnippet-0.13.0/doc/stylesheets...
    virtualbox-iso: Done (Total of 5 files compiled, 1 skipped in 2 directories)
    virtualbox-iso: (Spacemacs) --> installing package: zen-and-art-theme@themes-megapack... [263/264]
    virtualbox-iso: (Spacemacs) --> installing package: zenburn-theme@themes-megapack... [264/264]
    virtualbox-iso: Cannot open load file: No such file or directory, bind-map
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 255

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 255

==> Builds finished but no artifacts were created.
Makefile:10: recipe for target 'vms/base/instant-gnuradio-base.ova' failed
make: *** [vms/base/instant-gnuradio-base.ova] Error 1
➜  instant-gnuradio-master ls

**Comment by bastibl** [comment]
Looks like Spacemacs installation broke - again. If you don't need Spacemacs comment out these lines

https://github.com/bastibl/instant-gnuradio/blob/master/scripts/setup-base.sh#L41-L55

I probably should checkout the latest release version. Maybe that's more stable. I'll look into that.

**Comment by bastibl** [comment]
I just pushed a commit that should always use the most recent release of Spacemacs. I hope that's more stable. Feel free to reopen if you have still problems.
