### ISSUE TITLE
GNURadio Build Error

### ISSUE THREAD

**Issue by cyrus104** [bastibl/instant-gnuradio#14]
When the process gets to gnuradio, it's throwing an error.

virtualbox-ovf: PyBOMBS.Packager.source - DEBUG - Configuring recipe gnuradio
    virtualbox-ovf: PyBOMBS.Packager.source - DEBUG - Using vars - ordereddict([('config_opt', ' -DENABLE_DOXYGEN=$builddocs -DENABLE_GR_AUDIO=ON -DENABLE_GR_BLOCKS=ON -DENABLE_GR_DIGITAL=ON -DENABLE_GR_FEC=ON -DENABLE_GR_FFT=ON -DENABLE_GR_FILTER=ON -DENABLE_GR_QTGUI=ON -DENABLE_GR_UHD=ON -DENABLE_PYTHON=ON -DENABLE_VOLK=ON -DENABLE_GRC=ON '), ('builddir', '/home/gnuradio/pybombs/src/gnuradio/build')])
    virtualbox-ovf: PyBOMBS.Packager.source - DEBUG - In cwd - /home/gnuradio/pybombs/src/gnuradio/build
    virtualbox-ovf: PyBOMBS._process_thread() - DEBUG - Executing command `$ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/gnuradio/pybombs  -DENABLE_DOXYGEN=ON -DENABLE_GR_AUDIO=ON -DENABLE_GR_BLOCKS=ON -DENABLE_GR_DIGITAL=ON -DENABLE_GR_FEC=ON -DENABLE_GR_FFT=ON -DENABLE_GR_FILTER=ON -DENABLE_GR_QTGUI=ON -DENABLE_GR_UHD=ON -DENABLE_PYTHON=ON -DENABLE_VOLK=ON -DENABLE_GRC=ON  -Wno-dev'
    virtualbox-ovf: Configuring: [ |                                                       -- Build type set to RelWithDebInfo.
    virtualbox-ovf: -- Extracting version information from git describe...
    virtualbox-ovf: -- Compiler Version: cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
    virtualbox-ovf: Copyright (C) 2017 Free Software Foundation, Inc.
    virtualbox-ovf: This is free software; see the source for copying conditions.  There is NO
    virtualbox-ovf: warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    virtualbox-ovf: -- Compiler Flags: /usr/bin/cc:::-O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized
    virtualbox-ovf: /usr/bin/c++:::-O2 -g -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized
    virtualbox-ovf: -- ADDING PERF COUNTERS
    virtualbox-ovf: -- Building Static Libraries: OFF
    virtualbox-ovf: -- Boost version: 1.65.1
    virtualbox-ovf: -- Found the following Boost libraries:
    virtualbox-ovf: --   date_time
    virtualbox-ovf: --   program_options
    virtualbox-ovf: --   filesystem
    virtualbox-ovf: --   system
    virtualbox-ovf: --   regex
    virtualbox-ovf: --   thread
    virtualbox-ovf: --   unit_test_framework
    virtualbox-ovf: --   chrono
    virtualbox-ovf: --   atomic
    virtualbox-ovf: --
    virtualbox-ovf: -- Checking for module SWIG
    virtualbox-ovf: -- Found SWIG version 3.0.12.
    virtualbox-ovf: --
    virtualbox-ovf: -- The build system will automatically enable all components.
    virtualbox-ovf: -- Use -DENABLE_DEFAULT=OFF to disable components by default.
    virtualbox-ovf: --
    virtualbox-ovf: -- Configuring python-support support...
    virtualbox-ovf: --   Dependency PYTHONLIBS_FOUND = TRUE
    virtualbox-ovf: --   Dependency SWIG_FOUND = TRUE
    virtualbox-ovf: --   Dependency SWIG_VERSION_CHECK = TRUE
    virtualbox-ovf: --   Enabling python-support support.
    virtualbox-ovf: --   Override with -DENABLE_PYTHON=ON/OFF
    virtualbox-ovf: --
    virtualbox-ovf: -- Configuring testing-support support...
    virtualbox-ovf: --   Dependency Boost_FOUND = 1
    virtualbox-ovf: --   Enabling testing-support support.
    virtualbox-ovf: --   Override with -DENABLE_TESTING=ON/OFF
    virtualbox-ovf: --
    virtualbox-ovf: -- Configuring VOLK support...
    virtualbox-ovf: -- Build type set to RelWithDebInfo.
    virtualbox-ovf: -- Extracting version information from git describe...
    virtualbox-ovf: --
    virtualbox-ovf: -- Python checking for python >= 2.7
    virtualbox-ovf: -- Python checking for python >= 2.7 - found
    virtualbox-ovf: --
    virtualbox-ovf: -- Python checking for mako >= 0.4.2
    virtualbox-ovf: -- Python checking for mako >= 0.4.2 - found
    virtualbox-ovf: --
    virtualbox-ovf: -- Python checking for six - python 2 and 3 compatibility library
    virtualbox-ovf: -- Python checking for six - python 2 and 3 compatibility library - found
    virtualbox-ovf: -- Boost version: 1.65.1
    virtualbox-ovf: -- Found the following Boost libraries:
    virtualbox-ovf: --   filesystem
    virtualbox-ovf: --   system
    virtualbox-ovf: -- Checking for module 'orc-0.4 > 0.4.11'
    virtualbox-ovf: --   No package 'orc-0.4' found
    virtualbox-ovf: -- orc files (missing: ORC_LIBRARY ORC_INCLUDE_DIR ORCC_EXECUTABLE)
    virtualbox-ovf: -- QA Testing is enabled.
    virtualbox-ovf: --   Modify using: -DENABLE_TESTING=ON/OFF
    virtualbox-ovf: -- System profiling is disabled.
    virtualbox-ovf: --   Modify using: -DENABLE_PROFILING=ON/OFF
    virtualbox-ovf: -- Compiler name: GNU
    virtualbox-ovf: -- x86* CPU detected
    virtualbox-ovf: -- ORC support not found, Overruled arch orc
    virtualbox-ovf: -- CPU width is 64 bits, Overruled arch 32
    virtualbox-ovf: -- Available architectures: generic;64;3dnow;abm;popcount;mmx;fma;sse;sse2;norc;sse3;ssse3;sse4_a;sse4_1;sse4_2;avx;avx2
    virtualbox-ovf: -- Available machines: generic;sse2_64_mmx;sse3_64_mmx;ssse3_64_mmx;sse4_a_64_mmx;sse4_1_64_mmx;sse4_2_64_mmx;avx_64_mmx;avx2_64_mmx
    virtualbox-ovf: -- BUILD TYPE = RELWITHDEBINFO
    virtualbox-ovf: -- Base cflags = -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall
    virtualbox-ovf: -- BUILD INFO ::: generic ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall
    virtualbox-ovf: -- BUILD INFO ::: sse2_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2
    virtualbox-ovf: -- BUILD INFO ::: sse3_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3
    virtualbox-ovf: -- BUILD INFO ::: ssse3_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3
    virtualbox-ovf: -- BUILD INFO ::: sse4_a_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -msse4a -mpopcnt
    virtualbox-ovf: -- BUILD INFO ::: sse4_1_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1
    virtualbox-ovf: -- BUILD INFO ::: sse4_2_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt
    virtualbox-ovf: -- BUILD INFO ::: avx_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx
    virtualbox-ovf: -- BUILD INFO ::: avx2_64_mmx ::: GNU ::: -O2 -g -DNDEBUG  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mfma -mavx2
    virtualbox-ovf: -- Compiler Version: cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
    virtualbox-ovf: Copyright (C) 2017 Free Software Foundation, Inc.
    virtualbox-ovf: This is free software; see the source for copying conditions.  There is NO
    virtualbox-ovf: warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    virtualbox-ovf: -- c flags:  -std=gnu99 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall;
    virtualbox-ovf: -- asm flags:
    virtualbox-ovf: -- Did not find liborc and orcc, disabling orc support...
    virtualbox-ovf: -- Loading version 1.4 into constants...
    virtualbox-ovf: -- Using install prefix: /home/gnuradio/pybombs
    virtualbox-ovf: --
    virtualbox-ovf: -- Configuring volk support...
    virtualbox-ovf: --   Enabling volk support.
    virtualbox-ovf: --   Override with -DENABLE_VOLK=ON/OFF
    virtualbox-ovf: --   Override with -DENABLE_INTERNAL_VOLK=ON/OFF
    virtualbox-ovf: -- ENABLE_GR_LOG set to ON.
    virtualbox-ovf: -- HAVE_LOG4CPP set to True.
    virtualbox-ovf: -- LOG4CPP_LIBRARIES set to /usr/lib/x86_64-linux-gnu/liblog4cpp.so.
    virtualbox-ovf: -- Checking for module 'gmp'
    virtualbox-ovf: --   No package 'gmp' found
    virtualbox-ovf: -- Could NOT find GMP (missing: GMPXX_LIBRARY GMP_LIBRARY GMP_INCLUDE_DIR)
    virtualbox-ovf: -- Checking for module 'mpir >= 3.0'
    virtualbox-ovf: --   No package 'mpir' found
    virtualbox-ovf: -- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR)
    virtualbox-ovf: -- Could NOT find MPLIB (missing: MPLIBXX_LIBRARY MPLIB_LIBRARY MPLIB_INCLUDE_DIR)
    virtualbox-ovf: -- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
    virtualbox-ovf: --
    virtualbox-ovf: -- Configuring doxygen support...
    virtualbox-ovf: --   Dependency DOXYGEN_FOUND = YES
    virtualbox-ovf: --   Enabling doxygen support.
    virtualbox-ovf: --   Override with -DENABLE_DOXYGEN=ON/OFF
    virtualbox-ovf: --
    virtualbox-ovf: -- Configuring sphinx support...
    virtualbox-ovf: --   Dependency SPHINX_FOUND = FALSE
    virtualbox-ovf: --   Disabling sphinx support.
    virtualbox-ovf: --   Override with -DENABLE_SPHINX=ON/OFF
    virtualbox-ovf: -- Checking for module 'gmp'
    virtualbox-ovf: --   No package 'gmp' found
    virtualbox-ovf: -- Could NOT find GMP (missing: GMPXX_LIBRARY GMP_LIBRARY GMP_INCLUDE_DIR)
    virtualbox-ovf: -- Checking for module 'mpir >= 3.0'
    virtualbox-ovf: --   No package 'mpir' found
    virtualbox-ovf: -- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR)
    virtualbox-ovf: CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
    virtualbox-ovf:   Could NOT find MPLIB (missing: MPLIBXX_LIBRARY MPLIB_LIBRARY
    virtualbox-ovf:   MPLIB_INCLUDE_DIR)
    virtualbox-ovf: Call Stack (most recent call first):
    virtualbox-ovf:   /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    virtualbox-ovf:   cmake/Modules/FindMPLIB.cmake:26 (find_package_handle_standard_args)
    virtualbox-ovf:   gnuradio-runtime/CMakeLists.txt:26 (find_package)
    virtualbox-ovf:
    virtualbox-ovf:
    virtualbox-ovf: -- Configuring incomplete, errors occurred!
    virtualbox-ovf: See also "/home/gnuradio/pybombs/src/gnuradio/build/CMakeFiles/CMakeOutput.log".
    virtualbox-ovf: See also "/home/gnuradio/pybombs/src/gnuradio/build/CMakeFiles/CMakeError.log".
    virtualbox-ovf: PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
    virtualbox-ovf: PyBOMBS.monitor_process() - DEBUG - Return value: 1
    virtualbox-ovf: PyBOMBS.Packager.source - ERROR - Configuration failed after running at least twice.
    virtualbox-ovf: PyBOMBS.Packager.source - ERROR - Problem occurred while building package gnuradio:
    virtualbox-ovf: Configuration failed
    virtualbox-ovf: PyBOMBS.install_manager - ERROR - Error installing package gnuradio. Aborting.
    virtualbox-ovf: Configuring: (100%) [=========================================================]
==> virtualbox-ovf: Deregistering and deleting imported VM...
==> virtualbox-ovf: Deleting output directory...
Build 'virtualbox-ovf' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-ovf: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
make: *** [Makefile:13: vms/gnuradio/instant-gnuradio.ova] Error 1

**Comment by bastibl** [comment]
That's a bug of GNU Radio. The maintainer is aware of the issue and is working on a fix. 

http://lists.gnu.org/archive/html/discuss-gnuradio/2018-08/msg00158.html

**Comment by cyrus104** [comment]
This issue was partially a GMP / MPIR missing issue. I added the following to get it to compile.
scripts/setup-gnuradio line 45
`### GMP`
`pybombs -v install gmp`

**Comment by bastibl** [comment]
You're right. It's indeed yet another PyBombs bug. Since recently GNU Radio depends on GMP and the PyBombs receipt is not updated.
I just pushed a commit that does as you suggest https://github.com/bastibl/instant-gnuradio/commit/83091f2e61c25c27c2a70d76618b729808cd61bd

I'm not sure how to handle things like that in general. The script mutates into a big workaround for bugs in PyBombs and OOTs. It would be great if you could open an issue (or make a pull request) at gr-receipts so that this could be fixed upstream.

https://github.com/gnuradio/gr-recipes/blob/master/gnuradio.lwr#L20-L40
