### ISSUE TITLE
instant-gnuradio build fails during bladeRF configuration

### ISSUE THREAD

**Issue by jkbecker** [bastibl/instant-gnuradio#16]
Hi Basti,

I just rebuilt the VM from the most recent master branch, and I'm getting this (full install log linked, pointing to the error):
https://gist.github.com/jkbecker/9a9a8f6ad65a982ec2e09b71ec7e464d#file-make-log-L1227

I'll look into it in the meantime, but maybe it's a very obvious issue to you...?

Cheers, Johannes

**Comment by bastibl** [comment]
I'm also rebuilding atm. Nuand split udev rules in several files
```
sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf1.rules.in | sudo tee pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf1.rules
sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf2.rules.in | sudo tee pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf2.rules
sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bootloader.rules.in | sudo tee pybombs/src/bladeRF/host/misc/udev/88-nuand-bootloader.rules
```

**Comment by jkbecker** [comment]
Sweet. And an asterisk in the line after as well, right?

    sudo cp pybombs/src/bladeRF/host/misc/udev/88-nuand*.rules /etc/udev/rules.d/

**Comment by bastibl** [comment]
This line needs to be deleted. It directly pipes it to /etc

```
### BLADERF
pybombs -v install bladeRF
sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf1.rules.in | sudo tee pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf1.rules
sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf2.rules.in | sudo tee pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf2.rules
sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bootloader.rules.in | sudo tee pybombs/src/bladeRF/host/misc/udev/88-nuand-bootloader.rules
```

**Comment by jkbecker** [comment]
Wait, I'm confused... shouldn't these lines read as follows then (tee'ing to /etc)?

    ### BLADERF
    pybombs -v install bladeRF
    sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf1.rules.in | sudo tee /etc/udev/rules.d/88-nuand-bladerf1.rules
    sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bladerf2.rules.in | sudo tee /etc/udev/rules.d/88-nuand-bladerf2.rules
    sed 's/@BLADERF_GROUP@/plugdev/g' pybombs/src/bladeRF/host/misc/udev/88-nuand-bootloader.rules.in | sudo tee /etc/udev/rules.d/88-nuand-bootloader.rules

**Comment by bastibl** [comment]
arg, you're right... I don't have a BladeRF to test :-/

**Comment by jkbecker** [comment]
Me neither! I just want it to build, mostly ;)

**Comment by bastibl** [comment]
OK :-) The other stuff worked for me earlier today.
I'm trying to add support for the Pluto and then  push the changes.

**Comment by jkbecker** [comment]
Ah, cool!

Building without issues for me now.

**Comment by bastibl** [comment]
Great, I'll close this then. Thanks!
