### ISSUE TITLE
LimeSDR

### ISSUE THREAD

**Issue by cyrus104** [bastibl/instant-gnuradio#17]
Can you add support for the LimeSDR and LimeSDR Suite software?

Thanks

**Comment by bastibl** [comment]
I tried to add support for Lime and the XTRX, but I don't have the hardware to test. You can rebuild the image or download a pre-built one from https://www.fleark.de/instant-gnuradio.ova

Let me know if it works for you.

**Comment by bastibl** [comment]
I close this for now. Let me know if there's an issue with Lime.
