### ISSUE TITLE
Add XTRX SDR Support

### ISSUE THREAD

**Issue by cyrus104** [bastibl/instant-gnuradio#18]
Can you add support the XTRX SDR, this SDR is a USB3 and PCIE SDR with high bandwidth.

**Comment by bastibl** [comment]
Is PCIe forwarding to the VM even possible?

**Comment by cyrus104** [comment]
This device was designed to run over USB3 and PCIe, so there is no need to forward the PCIe to the VM. 

You live-cd boot will work be able to use this if it's connected to PCIe.

I really appreciate your work, I've been busy and haven't been able to test. Will start that in the next few days.

**Comment by bastibl** [comment]
ok, support should be in. Even though I couldn't test, since I don't have the HW.
