### ISSUE TITLE
Screen resolution is low for the VM.

### ISSUE THREAD

**Issue by Ghaz75** [bastibl/instant-gnuradio#35]
Hello Dear
Everything works fine except the annoying low resolution. I have tried scaling etc but there is no way I increase the resolution as per my 17" FHD 1920 x .... Screen. The VM gives resolution not greater than 800x 600. Any idea what is wrong with it. There is no option in the VBox which can help. Auto resize guest display is greyed.

**Comment by bastibl** [comment]
Hmm, sorry no idea. I have much higher resolution without any manual adjustment. What your host OS? Does it have all drivers installed? (At least on Linux, there are free and proprietary drivers. Don't know if this might cause issues.) Do other VMs work with higher resolution, i.e., are you sure it's a problem of this particular VM? On Linux, there is also a `vboxusers` group in which my user is. Not sure if this has an impact on graphics though.
