### ISSUE TITLE
Feature Request: Support Adalm Pluto in grc

### ISSUE THREAD

**Issue by eneukirchner** [bastibl/instant-gnuradio#42]
Could you possible add support for Adalm Pluto SDR as a block in gnuradio-companion?

**Comment by bastibl** [comment]
Unfortunately that's not so easy given the desperate packaging state. Ubuntu 20.04 comes with GNU Radio 3.8, but the gr-iio package is broken. At the moment, the VM uses a PPA. When it was built initially, this PPA had GNU Radio 3.8 with some compatible OOTs. If you rebuilt now, the PPA ships GNU Radio 3.9 but none of the OOTs are updated... I'm happy to update and rebuilt, but I want to avoid compiling OOTs from source (again) or using PyBombs. Maybe you could ask if someone would be motivated to update in-tree or PPA packages.

**Comment by eneukirchner** [comment]
There is hope https://www.youtube.com/watch?v=2gKbollW6wg

**Comment by bastibl** [comment]
Yes, but nothing that will happen soon :-/  GNU Radio 3.10 needs to be released and packaged, and then OOTs have to be ported to 3.10 and packaged. AFAIK, there will be some infrastructure work on GNU Radio, which might help to stream-line this process, but I'd assume that's >5 months. So, imho, it would still make sense to update the PPA.

**Comment by danielgallagher** [comment]
My fork has a branch that adds PlutoSDR support linked below. It was buildable and functional earlier this year. That may have changed over time. Feel free to give it a try. I would be interested hearing if it still builds successfully. 

https://github.com/danielgallagher/instant-gnuradio/tree/ua_ece531

I am happy to create a PR if @bastibl wants to verify and merge the updates. I agree that this a temporary solution until GNU Radio 3.10 is ready.

**Comment by bastibl** [comment]
Sorry, I missed this :-/ Now that 3.10 is out, it's probably better to go down that road.
