### ISSUE TITLE
Deprecated configuration key: 'iso_checksum_type'. 

### ISSUE THREAD

**Issue by stkrzysiak** [bastibl/instant-gnuradio#44]
When running `make` I get this error:

`Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.
`

`
packer --version
1.8.0
`

**Comment by BenGardiner** [comment]
resolved by #46
