### ISSUE TITLE
Ubuntu updated to 22.04.2

### ISSUE THREAD

**Issue by ryanmtaylor** [bastibl/instant-gnuradio#52]
Ubuntu was updated to 22.04.2 and so the links to 22.04.1 iso no longer work – I also couldn't get SSH to work in 22.04.2 – I can get the command line ssh running for the base image for 20.04.5 but the password won't work.

**Comment by bastibl** [comment]
I just pushed some changes. Can you try the most recent version please?

**Comment by garanovich** [comment]
I don’t know where it’s better to write, but wired network was not found in Vmware and there was no /etc/netplan/01-netcfg.yaml file. It helped to add a line to /etc/netplan/00-installer-config.yaml. Run 
`echo "  renderer: NetworkManager" | sudo tee -a /etc/netplan/00-installer-config.yaml && reboot`

**Comment by bastibl** [comment]
Thanks for the info. Could you please make a PR with the version that works for you? Then, I can test w/ VirtualBox.

**Comment by bastibl** [comment]
I'll close this, since the original issue is resolved (i.e., it uses Ubuntu 22.04.2). If there are still networking issues w/ vmware, please open a PR. Since I'm not sure where you added these lines.
